[package]
name = "FetchOnchainBars"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
lambda_runtime = "0.11.2"
tokio = { version = "1", features = ["macros"] }
reqwest = { version = "0.12.4", features = ["json"] }
futures = "0.3.30"
serde = "1.0.203"
