name: deploy-lambda
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y libssl-dev
    - name: Install cargo lambda
      run: |
        python -m pip install --upgrade pip
        pip install cargo-lambda
    - name: Test scanner
      run: |
        cargo test
    - name: Build lambda function
      run: |
        cd FetchOnchainBars
        cargo lambda build --release --arm64
    - name: Deploy lambda function
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd FetchOnchainBars
        cat ../aws_regions.txt | xargs -I {} cargo lambda deploy --region {} --role arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/LambdaBasic --binary-name FetchOnchainBars
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/onchain-scanner:latest
